# Generated by Django 5.0.2 on 2025-01-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('root', 'Root'), ('employee', 'Employee')], default='employee', max_length=10, verbose_name='account_type'),
        ),
    ]
