# Generated by Django 5.0.2 on 2025-01-10 06:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=10, unique=True, verbose_name='得意先コード')),
                ('customer_name', models.CharField(max_length=100, verbose_name='得意先名')),
                ('phone_number', models.CharField(max_length=15, verbose_name='電話番号')),
                ('postal_code', models.CharField(max_length=8, verbose_name='郵便番号')),
                ('address', models.CharField(max_length=200, verbose_name='住所')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
            ],
            options={
                'verbose_name': '得意先',
                'verbose_name_plural': '得意先一覧',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=10, unique=True, verbose_name='製品コード')),
                ('product_name', models.CharField(max_length=100, verbose_name='製品名')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='単価')),
            ],
            options={
                'verbose_name': '製品',
                'verbose_name_plural': '製品一覧',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=10, unique=True, verbose_name='受注コード')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='受注日')),
                ('delivery_date', models.DateField(verbose_name='納品予定日')),
                ('delivered_date', models.DateField(blank=True, null=True, verbose_name='納品日')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customer', verbose_name='得意先')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.product', verbose_name='製品')),
            ],
            options={
                'verbose_name': '受注',
                'verbose_name_plural': '受注一覧',
            },
        ),
    ]
