# Generated by Django 5.0.2 on 2025-01-17 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='在庫数')),
                ('safety_stock', models.IntegerField(default=100, verbose_name='安全在庫数')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最終更新日')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='sales.product', verbose_name='製品')),
            ],
            options={
                'verbose_name': '在庫',
                'verbose_name_plural': '在庫一覧',
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', '入庫'), ('out', '出庫'), ('adjust', '在庫調整')], max_length=10, verbose_name='取引種類')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='取引日時')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='備考')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='sales.inventory', verbose_name='在庫')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.order', verbose_name='関連受注')),
            ],
            options={
                'verbose_name': '在庫取引',
                'verbose_name_plural': '在庫取引履歴',
            },
        ),
    ]
